import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerBackBtn: {
    width: 40,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  headerCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 6,
    minWidth: 0,
  },
  headerAvatarRing: {
    padding: 1.5,
    borderRadius: 999,
    borderWidth: 1.5,
  },
  headerAvatarLg: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  headerSubtitle: {
    fontSize: 12,
    fontWeight: '600',
  },
  headerSpacer: {
    width: 44,
  },
  offerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
  },
  offerPillText: {
    fontSize: 13,
    fontWeight: '800',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
    flexShrink: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    textAlign: 'center',
  },
  emptySubtext: {
    marginTop: 8,
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  messagesContent: {
    paddingVertical: 16,
  },
  unreadDividerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 14,
    marginVertical: 8,
  },
  unreadDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
  },
  unreadDividerPill: {
    borderRadius: 12,
    paddingHorizontal: 10,
    minHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadDividerText: {
    fontSize: 11,
    fontWeight: '800',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    gap: 8,
  },
  /** No background and no border of its own — the row sits directly on the chat area. */
  composerShell: {
    paddingHorizontal: 8,
    paddingTop: 6,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    position: 'relative',
    minHeight: 38,
  },
  composerIdleCluster: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  composerIdleClusterHidden: {
    opacity: 0,
  },
  /** The input's own rounded field — this is the one card that stays. */
  composerField: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 3,
    minHeight: 38,
    maxHeight: 120,
    justifyContent: 'center',
  },
  /** Plain icons beside the field — no filled circle behind them. */
  fieldIcon: {
    width: 34,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceSlot: {
    minWidth: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  voiceSlotRecording: {
    ...StyleSheet.absoluteFillObject,
    left: 0,
    right: 0,
    alignItems: 'stretch',
    justifyContent: 'center',
    zIndex: 2,
  },
  circleAction: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendCircle: {
    marginBottom: 0,
  },
  composerInput: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    maxHeight: 100,
    paddingVertical: Platform.OS === 'ios' ? 6 : 5,
    padding: 0,
  },
  inlineOfferButton: {
    width: '100%',
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  inlineOfferButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  text: {
    fontSize: 18,
  },
  button: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  offerModalCard: {
    width: '100%',
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  offerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  offerModalTitle: {
    fontSize: 17,
    fontWeight: '800',
  },
  offerLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  offerSpacingTop: {
    marginTop: 10,
  },
  offerInput: {
    marginTop: 6,
    borderWidth: 1,
    borderRadius: 12,
    height: 46,
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  offerNoteInput: {
    minHeight: 88,
    height: undefined,
    textAlignVertical: 'top',
    paddingTop: 10,
  },
  offerSubmitButton: {
    marginTop: 14,
    minHeight: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerSubmitText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  recordingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginBottom: 8,
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  recordingText: {
    fontSize: 12,
    fontWeight: '700',
  },
});
